title: Hello, world! I'm Sarah Du
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sarah Du # add your name
author-img: sarah_du.jpg # add your photo
about-author: Quantitative professional specialized in multi-asset class return and risk forecasts, factor analysis, total portfolio asset allocation, investment research, and multi-client portfolio management # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
#social-github: # add your Github handle
social-linkedin: https://www.linkedin.com/in/shuang-sarah-du-31b817120/# add your Linkedin handle
social-email: sarahdu0220@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
